// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhps8u4kUCBqZIpdRWwUbHrVERk1qL88o',
    appId: '1:846393151203:web:dd74e1e9e98d7c54ee7fd6',
    messagingSenderId: '846393151203',
    projectId: 'fyp-decoders',
    authDomain: 'fyp-decoders.firebaseapp.com',
    storageBucket: 'fyp-decoders.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnD1tiIzWALP56ZkO0wIWj3nLeEoVukWY',
    appId: '1:846393151203:android:5a85c28f1af87f7cee7fd6',
    messagingSenderId: '846393151203',
    projectId: 'fyp-decoders',
    storageBucket: 'fyp-decoders.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWkGGJ7G4LkSUBMIX-tgxpKfqyFEue9n4',
    appId: '1:846393151203:ios:16154ebbb0de3e4eee7fd6',
    messagingSenderId: '846393151203',
    projectId: 'fyp-decoders',
    storageBucket: 'fyp-decoders.appspot.com',
    iosBundleId: 'com.example.decoders',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWkGGJ7G4LkSUBMIX-tgxpKfqyFEue9n4',
    appId: '1:846393151203:ios:f8685e469a740c9cee7fd6',
    messagingSenderId: '846393151203',
    projectId: 'fyp-decoders',
    storageBucket: 'fyp-decoders.appspot.com',
    iosBundleId: 'com.example.decoders.RunnerTests',
  );
}
